### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by carlosRMago** [almondnguyen/android_OTA#2]
greetings almondnguyen I hope you are well, I found your code in the XDA forum published by ProveN I am eager to install it but at the same time my economy tells me to run out of phone if something goes wrong, anyway I would like to help, it has some errors like RIL among others according to the comments, I would like to know the advances and the inconveniences it has to test them first in an emulator, I am afraid because I have the money counted, thank you

**Comment by almondnguyen** [comment]
I'm also Prove N. (on XDA), mind you. And thank you in advance for the initiative.

So for the ROM on XDA, the bug should be these:
- Either RIL or Audio (which means you can only have one of those working). The instruction is already on XDA.
- Recent key (Although I have it fixed and pushed to Telegram group for J2 Prime, specifically: https://t.me/grandpplte/85005 ).
- SD Card reading from 3rd party app (also fixed, build above).
- The rest is pretty much the same on that XDA post, minus that _(bad bug)_, if you use the build above.

Various stuff:
- The instruction is a little bit different if you use the above build. If you want RIL, just delete or rename `/system/lib/hw/audio.primary.mt6735.so` and it'll be up.
- all RIL components are "working", that means SMS and Mobile Data works, Call "works" but no audio because as mentioned, to get RIL is to remove audio.

Again, tysm for the offer. I'd like to know how to test ROM in emulator though.

Best regards.

**Comment by almondnguyen** [comment]
(since there's no interaction, I'll close this. Thanks for understanding)
